### ISSUE TITLE
Вынести получение конфигов в конструктор

### ISSUE THREAD

**Issue by coder1coder** [brown-aleks/CleannetCode_bot#1]
https://github.com/brown-aleks/CleannetCode_bot/blob/bbbb0b23caa439ad83b58ea521b14d9ef6d6e88e/CleannetCode_bot/BotService.cs#L25

**Comment by brown-aleks** [comment]
**config** заходит через конструктор и хранится в приватном поле только для чтения.

**Comment by brown-aleks** [comment]
> https://github.com/brown-aleks/CleannetCode_bot/blob/bbbb0b23caa439ad83b58ea521b14d9ef6d6e88e/CleannetCode_bot/BotService.cs#L25

**config** заходит через конструктор и хранится в приватном поле только для чтения.

**Comment by coder1coder** [comment]
Как минимум странно что тебе весь конфиг приложения доступен в классе. Во вторых, зачем каждый раз получать accessToken внутри метода (да, оно может вызываться 1 раз, а может и нет), если можно 1 раз в конструкторе?
