### ISSUE TITLE
Использовать дженерик

### ISSUE THREAD

**Issue by coder1coder** [brown-aleks/CleannetCode_bot#2]
https://github.com/brown-aleks/CleannetCode_bot/blob/bbbb0b23caa439ad83b58ea521b14d9ef6d6e88e/CleannetCode_bot/IStorageService.cs#L5

**Comment by brown-aleks** [comment]
Замечание очень правильное. Мне такая передача параметром то же не нравится. Это временное...
Сейчас продумываю способы зависимостей от **BotService** до **IStorageService**.
Дело в том что между ними ещё должна располагаться бизнес логика. и нужно сохранить возможность подключать другие типы хранилища данных. Например из тех которые поддерживает EF. Пока думаю как это реализовать.

**Comment by brown-aleks** [comment]
Исправил. Можно будет наблюдать в следующем коммите.
