### ISSUE TITLE
Объеденить в одно условие

### ISSUE THREAD

**Issue by temkinman** [brown-aleks/CleannetCode_bot#3]
https://github.com/brown-aleks/CleannetCode_bot/blob/bbbb0b23caa439ad83b58ea521b14d9ef6d6e88e/CleannetCode_bot/StorageFileService.cs#L31-L33

if(obj is null || type is null || methodName is null) return Task.CompletedTask

**Comment by brown-aleks** [comment]
Так и сделал. Точнее, после рефакторинга осталось одно условие. В следующей версии всё будет исправлено. Спасибо за комментарии.
